language: dart
dart:
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings lib

script:
  - pub run test -r expanded test/*.dart
  - pub get --packages-dir
  - pub global activate coverage
  - pub global activate coveralls
  - dart --observe=8111 test/*.dart &
  - sleep 30
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
  - pub global run coverage:format_coverage --package-root=lib --report-on lib --in coverage.json --out coverage.lcov --lcov

after_success:
  - pub global run coveralls coverage.lcov