language: dart
dart:
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings lib

script:
  - pub run test -r expanded test/*.dart
  - pub get --packages-dir
  - pub global activate coverage
  - pub global activate coveralls
  - pub run dart_codecov_generator --report-on=lib/ --verbose
  
after_success:
  - pub global run coveralls coverage.lcov