language: dart
dart:
  - dev

dart_task:
  - test
  - dartanalyzer: --fatal-warnings lib

install:
  - pub global activate coveralls
  - pub global activate coverage

script:
  - pub get
  - pub run test -r expanded test/*.dart
  - dart --observe=8111 test/*.dart
  - sleep 3
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
  - pub global run coverage:format_coverage --package-root=lib --report-on lib --in coverage.json --out coverage.lcov --lcov

after_success:
  - pub global run coveralls coverage.lcov