language: dart
dart:
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings lib

script:
  - pub run test -r expanded test/*.dart
  - pub get
  - pub global activate coverage
  - pub global activate coveralls
  - dart --pause-isolates-on-exit --enable-vm-service=8111 --checked test/*.dart & sleep 5
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
  - pub global run coverage:format_coverage --packages=.packages --report-on lib --in coverage.json --out coverage.lcov --lcov

after_success:
  - pub global run coveralls coverage.lcov