name: stay_points
description: Stay points/meaningful locations identification
version: 0.0.6
homepage: https://www.yeradis.com
author: Yeradis P. Barbosa Marrero <yeradis@gmail.com>

dependencies:
  great_circle_distance: ^0.0.5

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
