name: stay_points
description: Stay points/meaningful locations identification
version: 0.0.8
homepage: https://www.yeradis.com
author: Yeradis P. Barbosa Marrero <yeradis@gmail.com>

dependencies:
  great_circle_distance: ^0.0.6

environment:
  sdk: '>=1.20.1'

dev_dependencies:
  test: ^0.12.0
  coverage: "^0.7.0"
  dart_codecov_generator: "^0.4.0"