name: stay_points
description: Stay-point Identification for Dart
version: 0.0.1
homepage: https://www.yeradis.com
author: yeradis <yeradis@gmail.com.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
